### Trip preview
POST http://127.0.0.1:8081/trip/preview
Content-Type: application/json

{
    "userID": "12",
    "destination": {
        "latitude": 37.7960377140795,
        "longitude": -122.42859007644311
    },
    "pickup": {
        "latitude": 37.783678087129466,
        "longitude": -122.40777303207217 
    }
}